version: '3.2'

services:

  # frontend:
  #   build: frontend
  #   ports:
  #     - 20080:80
  #   volumes:
  #     # Re-use local composer cache via host-volume
  #     - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #     # Mount source-code for development
  #     - ./:/app

  # backend:
  #   build: backend
  #   ports:
  #     - 21080:80
  #   volumes:
  #     # Re-use local composer cache via host-volume
  #     - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #     # Mount source-code for development
  #     - ./:/app

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=verysecret
  #     - MYSQL_DATABASE=yii2advanced
  #     - MYSQL_USER=yii2advanced
  #     - MYSQL_PASSWORD=secret

  pgsql:
   image: postgres
   environment:
     - POSTGRES_DB=yii2advanced
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
   ports:
     - "5433:5432"
  pgadmin:
   image: dpage/pgadmin4
   environment:
    - PGADMIN_DEFAULT_EMAIL=admin@test.com
    - PGADMIN_DEFAULT_PASSWORD=admin
   ports:
    - "8080:80"